package commit

import (
	"github.com/jesseduffield/lazygit/pkg/config"
	. "github.com/jesseduffield/lazygit/pkg/integration/components"
)

var CommitWithLlm = NewIntegrationTest(NewIntegrationTestArgs{
	Description:  "Generate commit message using LLM and commit changes",
	ExtraCmdArgs: []string{},
	Skip:         false,
	SetupConfig: func(appConfig *config.AppConfig) {
		// Configure LLM to be enabled with a simple test command
		appConfig.UserConfig.LLM.Enabled = true
		appConfig.UserConfig.LLM.Command = "echo 'feat: auto-generated commit message\n\nThis commit was generated by the LLM integration'"
	},
	SetupRepo: func(shell *Shell) {
		shell.
			CreateFile("test.txt", "initial content").
			CreateFile("test2.txt", "another file")
	},
	Run: func(t *TestDriver, keys config.KeybindingConfig) {
		t.Views().Commits().
			IsEmpty()

		t.Views().Files().
			IsFocused().
			Lines(
				Contains("test.txt"),
				Contains("test2.txt"),
			).
			SelectNextItem().
			PressPrimaryAction(). // stage first file
			Press(keys.Files.CommitChangesWithLLM)

		// The commit message panel should open with the generated message
		t.ExpectPopup().CommitMessagePanel().
			InitialText(Contains("feat: auto-generated commit message")).
			Type(""). // Don't add anything, just use the generated message
			Confirm()

		// Verify the commit was created with the generated message
		t.Views().Commits().
			Lines(
				Contains("feat: auto-generated commit message"),
			)

		// Verify the file is no longer in the files view (it's been committed)
		t.Views().Files().
			Lines(
				Contains("test2.txt"), // Only unstaged file remains
			)
	},
})